#!/bin/sh
EDIR=.
# les jars associes
EJAR=${EDIR}/eggc-6.0.0.jar:.
GJAR=${EJAR}:.

#--------------------------------------------------------
# java, javac, jar
#JDIR=/usr/local/jdk1.6/bin
JDIR=/usr/bin

cd ${SCRIPT_PATH:-.}
${JDIR}/java -classpath .:${GJAR} moc.compiler.MOCC $*
